version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /home/app/
      - /home/app/node_modules
    depends_on:
      - db
    networks:
      - app-network
    command: sh -c 'yarn && yarn dev'
  db:
    container_name: mypsql
    image: postgres
    restart: always
    env_file:
      - .env  
    ports:
      - "5432:5432"
    networks:
      - app-network
  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - app-network
    links:
      - db:pg-server
    logging:
      driver: "none"