export const MESSAGE = {
    CREATE_CAMPAIGN_SUCCESS: 'Created campaign successfully',
    UPDATE_CAMPAIGN_SUCCESS: 'Updated campaign successfully',
    DELETE_CAMPAIGN_SUCCESS: 'Deleted campaign successfully',
    CAMPAIGN_NOT_FOUND: 'Not found campaign of this organization',
    CAMPAIGN_NOT_FOUND_BY_CLIENT: 'Not found campaign',
    CAMPAIGN_TIME_INAPPROPRIATE: 'Cannot register this campaign now',
    NOT_BELONG_TO_ORGANIZATION: 'This organization does not belong to you',
    REGISTER_VOLUNTEER_SUCCESS: 'Registered volunteer successfully',
    REGISTER_DONOR_SUCCESS: 'Registered donor successfully',
    VOLUNTEER_ALREADY_REGISTERED: 'Volunteer already registered',
    VOLUNTEER_NOT_FOUND: 'Volunteer not found',
    UPDATE_VOLUNTEER_STATUS_SUCCESS: 'Updated volunteer status successfully',
    SET_PENDING_VOLUNTEERS_STATUS_TO_REJECTED_SUCCESS: 'Set pending volunteers status to rejected successfully',
    CREATE_DONATION_SUCCESS: 'Created donation successfully',
    DONATION_NOT_FOUND: 'Donation not found',
    DELETE_DONATION_SUCCESS: 'Deleted donation successfully',
    UPDATE_DONATION_SUCCESS: 'Updated donation successfully',
    UPDATE_DONATION_STATUS_SUCCESS: 'Updated donation status successfully',
    SET_PENDING_DONATIONS_STATUS_TO_REJECTED_SUCCESS: 'Set pending donations status to rejected successfully',
};
