export const MESSAGE = {
    CREATE_CAMPAIGN_SUCCESS: 'Created campaign successfully',
    UPDATE_CAMPAIGN_SUCCESS: 'Updated campaign successfully',
    DELETE_CAMPAIGN_SUCCESS: 'Deleted campaign successfully',
    CAMPAIGN_NOT_FOUND: 'Not found campaign of this organization',
    CAMPAIGN_NOT_FOUND_BY_CLIENT: 'Not found campaign',
    NOT_BELONG_TO_ORGANIZATION: 'This organization does not belong to you',
    REGISTER_VOLUNTEER_SUCCESS: 'Registered volunteer successfully',
    REGISTER_DONOR_SUCCESS: 'Registered donor successfully',
    VOLUNTEER_ALREADY_REGISTERED: 'Volunteer already registered',
    DONOR_ALREADY_REGISTERED: 'Donor already registered',
    VOLUNTEER_NOT_FOUND: 'Volunteer not found',
    UPDATE_VOLUNTEER_STATUS_SUCCESS: 'Updated volunteer status successfully',
    SET_PENDING_VOLUNTEERS_STATUS_TO_REJECTED_SUCCESS: 'Set pending volunteers status to rejected successfully',
};
