export const ERROR_CODE = {
    BAD_REQUEST: 'BAD_REQUEST',
    NOT_FOUND: 'NOT_FOUND',
    UNIQUE_CONSTRAINT: 'UNIQUE_CONSTRAINT',
    DUPLICATED: 'DUPLICATED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL: 'INTERNAL',
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY'
};
